[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
sea-orm = { version = "1.0.0-rc.5" }
uuid = {version = "1.11.0",features = ["v4","fast-rng","macro-diagnostics"]}